### ISSUE TITLE
Can not open the description of your methods and results link

### ISSUE THREAD

**Issue by numb123-duoduo** [mattdutson/xview2#3]
Hello,thank you for sharing your code! Your code is very logical and I want to learn more from you. But when I want to study the detailed description of your proposed method, I find that the website you shared cannot be opened. Therefore, could you please re-share a detailed description of the theory and results? I would be very grateful.

**Comment by mehmetfdemirel** [comment]
Thanks for your interest! Please try the given link again as it should be fixed now.

**Comment by numb123-duoduo** [comment]
Thank you for your prompt reply! I am looking forward to more communication with you.



---Original---
From: "Mehmet F. ***@***.***&gt;
Date: Tue, Aug 9, 2022 11:41 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mattdutson/xview2] Can not open the description of your methods and results link (Issue #3)




 
Closed #3 as completed.

**Comment by mattdutson** [comment]
Thanks for taking care of this Mehmet!
